name: initial_runnable_state
description: The Flutter package for getting `Context` in `initState()` callback of State.
version: 0.0.1
homepage: https://github.com/youmitsu/InitialRunnableState
documentation: https://github.com/youmitsu/InitialRunnableState/README.md
author: Yu Mitsuhori <mitsuhoriyu@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
